### ISSUE TITLE
local file upload default to .apj but require .hex to complete

### ISSUE THREAD

**Issue by nkruzan** [ArduPilot/ArduConfigurator#7]
https://github.com/ArduPilot/ArduConfigurator/blob/14afe30f712680b295484ff5f0be5bdfbcf3de50/tabs/firmware_flasher.js#L249

fails with hex corrupted error when choosing .apj file to upload. changing file type to all files in open dialog and choosing a .hex succeeds

i guess around line 264 need to check file type and call parse_hex or parse_apj as appropriate, instead of just blindly calling parse_hex?

**Comment by davidbuzz** [comment]
Yep.

**Comment by nkruzan** [comment]
implemented by @davidbuzz thanks!
